### ISSUE TITLE
Add bundlesize to keep track of generated files size

### ISSUE THREAD

**Issue by Idered** [eyedea-io/webmaster-kit#14]
https://github.com/siddharthkp/bundlesize

**Comment by sasalx** [comment]
I can take this. Do you have a preferable max size for the bundle?

**Comment by Idered** [comment]
@sasalx you can check [this article ](https://developers.google.com/web/fundamentals/performance/webpack/monitor-and-analyze) to find out the sizes.

**Comment by sasalx** [comment]
Yea I did that before but seems like you can add max size limit to project. Do you want something like that?

**Comment by Idered** [comment]
I would like to have max size for these files

```
.build/**/main.*.js - 200KiB
.build/**/*.js - 30KiB
```

0.d3dba71557fc91b13178.chunk.js
1.d3dba71557fc91b13178.chunk.js

both should have 30KiB limit

main.d3dba71557fc91b13178.chunk.js
should have 200KiB limit


You can run `npm run build website` to check generated files.

**Comment by Idered** [comment]
Also max size for images:

```
.build/**/*.png - 1MB
.build/**/*.jpg - 700 KiB
```
