### ISSUE TITLE
Replace yarn with npm 

### ISSUE THREAD

**Issue by mkucharz** [eyedea-io/webmaster-kit#3]
I don't see any advantages of using Yarn over NPM. As far as I know NPM is faster now than Yarn. Also probably much more popular.

**Comment by Idered** [comment]
I'll run tests and check which one is faster

**Comment by mkucharz** [comment]
Advantage of NPM from the other hand is that it is already installed. The only reason which may be worth to stay with yarn is speed or particular features NPM don’t have.
